# Generated by Django 3.1.13 on 2021-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='description',
            new_name='opt1',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='que',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='opt2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='opt3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='opt4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='que_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
