# Generated by Django 3.1.13 on 2021-12-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20211208_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='opt1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='opt2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='opt3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='opt4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
